name: Cache dependencies

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
       file-name: ${{ steps.publish.outputs.file-output}}
       cache-dir: ${{ steps.cache.outputs.dir }}
    steps:
    - name: Download Code
      uses: actions/checkout@v3.3.0
    - name: Get cache directory
      id: cache
      run: |
         echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
    - name: Cache dependencies
      uses: actions/cache@v3.2.6
      with:
        path: $${{ steps.cache.outputs.dir }}
        key: "dep-node-${{ hashFiles('**/package-lock.json') }}"        
    - name: Install dependency
      run: |
        npm ci
    - name: Lint code
      run: |
        npm run lint
    - name: Test code
      run: |
       npm run test
    - name: Build Code
      run: |
       npm run build
    - name: Get file name
      id: publish
      run: |
         find dist/assets/*.js -type f -execdir echo 'file-output={}' >> $GITHUB_OUTPUT ';'
         echo $GITHUB_OUPUT
    - name: List files and folders
      run: |
         ls -alt
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: dist-files
        path: |
          dist
         
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Printing cache directory
      run: |
         echo ${{ needs.build.outputs.cache-dir }}
    - name: Download Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: dist-files
    - name: Check downloads
      run: |
         ls -alt
    - name: Checking file name
      run: |
         echo "${{ needs.build.outputs.file-name }}"     
    - name: Deploy code
      run: |
       echo "Deploying Artifact"
      
      
