name: "Build Test workflow"

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Lint Code
      run: |
        echo "Linting code"
        npm lint
    - name: Build code
      run: |
         echo "Building code"
         npm build
    - name: Test code
      run: |
         echo "Running tests"
         npm test