name: Lint Build Test Workflow

on:
  workflow_dispatch:
  
jobs:
  lint:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout Code
     uses: actions/checkout@v3.3.0
   - name: Install Dependencies
     run: |
       npm ci
   - name: Run Lint
     run: |
       npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.3.0
    - name: Install Dependencies
      run: |
        npm ci
    - name: Run test
      run: |
         npm run test
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3.3.0
    - name: Install Dependencies
      run: |
        npm ci
    - name: Run build
      run: |
         npm run build

